version: "3.8"
services:
    ansible-molecule:
        container_name: ansible-molecule
        image: ansible
        # restart: always
        privileged: true
        stdin_open: true
        tty: true
        ports:
          - "22:22"
        volumes:
            - //var/run/docker.sock:/var/run/docker.sock
